intuity:
    image: atmoz/sftp
    volumes:
        - ./data/intuity/data:/home/intuity/data
        - ./data/intuity/tmp:/home/intuity/tmp
    ports:
        - "7777:22"
    command: intuity:pass:1001
intervent:
    image: atmoz/sftp
    volumes:
        - ./data/intervent/data:/home/intervent/data
        - ./data/intervent/tmp:/home/intervent/tmp
    ports:
        - "8888:22"
    command: intervent:pass:1001
