version: '2'
services:
  intuity:
      image: atmoz/sftp
      volumes:
          - ./data/intuity/data:/home/intuity/data
          - ./data/intuity/tmp:/home/intuity/tmp
      ports:
          - "7777:22"
      command: intuity:pass:1001
  intervent:
      image: atmoz/sftp
      volumes:
          - ./data/intervent/data:/home/intervent/data
          - ./data/intervent/tmp:/home/intervent/tmp
      ports:
          - "8888:22"
      command: intervent:pass:1001
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
  ftpboy:
      build: .
      env_file: .env
      depends_on:
        - intuity
        - intervent
        - redis
