default: &default
  errors:
    opendir!:
      2:
        error: 'Validic::DirNotFoundError'
        message: <%= 'operation opendir! failed - dir not found! '%>
      3:
        error: 'Validic::DirAccessDeniedError'
        message: <%= 'operation opendir! failed - forbidden! '%>
    upload!:
      2:
        error: 'Validic::DirNotFoundError'
        message: <%= 'operation upload! failed - invalid path' %>
      3:
        error: 'Validic::DirAccessDeniedError'
        message: <%= 'operation upload! failed - access denied' %>
  ftp_sources:
    intervent:
      host: <%= ENV.fetch('INTERVENT_FTP_HOST', 'localhost') %>
      username: <%= ENV.fetch('INTERVENT_FTP_USER', 'intervent') %>
      password: <%= ENV.fetch('INTERVENT_FTP_PASSWORD', 'pass') %>
      port: <%= ENV.fetch('INTERVENT_FTP_PORT', '8888') %>
      dirs:
        sending: 'data/from'
        receiving: 'data/to'
        archiving: 'data/history'
    intuity:
      host: <%= ENV.fetch('INTUITY_FTP_HOST', 'localhost') %>
      username: <%= ENV.fetch('INTUITY_FTP_USER', 'intuity') %>
      password: <%= ENV.fetch('INTUITY_FTP_PASSWORD', 'pass') %>
      port: <%= ENV.fetch('INTUITY_FTP_PORT', '7777') %>
      dirs:
        sending: 'data/from'
        receiving: 'data/to'
        archiving: 'data/history'

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
