default: &default
  ftp_sources:
    intervent:
      host: <%= ENV.fetch('INTERVENT_FTP_HOST', 'localhost') %>
      username: <%= ENV.fetch('INTERVENT_FTP_USER', 'intervent') %>
      password: <%= ENV.fetch('INTERVENT_FTP_PASSWORD', 'pass') %>
      port: <%= ENV.fetch('INTERVENT_FTP_PORT', '8888') %>
    intuity:
      host: <%= ENV.fetch('INTUITY_FTP_HOST', 'localhost') %>
      username: <%= ENV.fetch('INTUITY_FTP_USER', 'intuity') %>
      password: <%= ENV.fetch('INTUITY_FTP_PASSWORD', 'pass') %>
      port: <%= ENV.fetch('INTUITY_FTP_PORT', '7777') %>

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
